In [1]:
import requests
from bs4 import BeautifulSoup
base_url="https://subslikescript.com/movies?page={}"
movie_title=[]
movie_link=[]
for page in range(1,6):
    url=base_url.format(page)
    #print(url)

    res=requests.get(url)
   # print(res)
    soup=BeautifulSoup(res.text,"html.parser")
    #print(soup)

    movie_conatiner=soup.find("ul",class_="scripts-list")
    #print(movie_container)

    movies=movie_conatiner.find_all('a')
   #print(movies)

    for movie in movies:
        title=movie.text.strip()
        movie_title.append(title)


        link="https://subslikescript.com"+movie['href']
        movie_link.append(link)

In [2]:
website="30 Most Popular Movies Right Now_ What to Watch In Theaters and Streaming __ Rotten Tomatoes – Movie and TV News.html"
file=open(website, encoding="utf-8")
res=file.read()
#print(res)
titles=[]
ratings=[]
soup=BeautifulSoup(res,"html.parser")
#print(soup)

movies=soup.find_all('div',class_="countdown-item")
#print(movies)

for movie in movies[:30]:
    titles.append(movie.h2.a.text)
    ratings.append(movie.find('span',class_="tMeterScore").text)
    
print(len(titles))

30

In [3]:
ratings=soup.find_all('span',class_="tMeterScore")
print(ratings)
print(len(ratings))

[<span class="tMeterScore">53%</span>, <span class="tMeterScore">96%</span>, <span class="tMeterScore">67%</span>, <span class="tMeterScore">63%</span>, <span class="tMeterScore">99%</span>, <span class="tMeterScore">56%</span>, <span class="tMeterScore">98%</span>, <span class="tMeterScore">27%</span>, <span class="tMeterScore">92%</span>, <span class="tMeterScore">68%</span>, <span class="tMeterScore">82%</span>, <span class="tMeterScore">94%</span>, <span class="tMeterScore">97%</span>, <span class="tMeterScore">58%</span>, <span class="tMeterScore">76%</span>, <span class="tMeterScore">83%</span>, <span class="tMeterScore">91%</span>, <span class="tMeterScore">33%</span>, <span class="tMeterScore">93%</span>, <span class="tMeterScore">95%</span>, <span class="tMeterScore">94%</span>, <span class="tMeterScore">80%</span>, <span class="tMeterScore">36%</span>, <span class="tMeterScore">90%</span>, <span class="tMeterScore">57%</span>, <span class="tMeterScore"></span>, <span class="tMeterScore">50%</span>, <span class="tMeterScore">88%</span>, <span class="tMeterScore">87%</span>, <span class="tMeterScore">92%</span>]
30

In [4]:
import pandas as pd
df=pd.DataFrame({
    'titles':titles,
    'ratings':ratings
})
df

                                     titles ratings
0          Transformers: Rise of the Beasts   [53%]
1       Spider-Man: Across the Spider-Verse   [96%]
2                        The Little Mermaid   [67%]
3                             The Boogeyman   [63%]
4     Are You There God? It's Me, Margaret.   [99%]
5                                    Fast X   [56%]
6                                BlackBerry   [98%]
7                               The Machine   [27%]
8                                   Reality   [92%]
9                               Flamin' Hot   [68%]
10           Guardians of the Galaxy Vol. 3   [82%]
11                                Blue Jean   [94%]
12                               Past Lives   [97%]
13              The Super Mario Bros. Movie   [58%]
14                 Avatar: The Way of Water   [76%]
15               Guy Ritchie's The Covenant   [83%]
16                                Bumblebee   [91%]
17                                Nefarious   [33%]
18                                     Sisu   [93%]
19                     You Hurt My Feelings   [95%]
20                     John Wick: Chapter 4   [94%]
21                           Leave No Trace   [80%]
22                          About My Father   [36%]
23  Dungeons & Dragons: Honor Among Thieves   [90%]
24                             Transformers   [57%]
25                                 My Fault      []
26                         A Beautiful Life   [50%]
27     The Angry Black Girl and Her Monster   [88%]
28                                  Missing   [87%]
29                                      Air   [92%]

In [5]:
website="Fact-checks _ PolitiFact.html"
file=open(website,encoding="utf-8")
res=file.read()
soup=BeautifulSoup(res,"html.parser")
statements=[]
sources=[]
dates=[]

articles=soup.find_all("article",class_="m-statement")

for article in articles:
    sources.append(article.find('a',class_="m-statement__name").text.strip())
    statements.append(article.find('div',class_="m-statement__quote").text.strip())
    dates_on=article.find('div',class_="m-statement__desc").text.strip().split('stated on')[1]
    dates.append(dates_on.split('in')[0])

In [6]:
df=pd.DataFrame({'staements':statements,
                 'sources':sources,
                 "date":dates})
df

,staements,sources,date
0,“President Trump’s tariffs are costing New Yor...,Kirsten Gillibrand,"March 19, 2026"
1,"""There's been numerous other occasions over th...",Donald Trump,"May 18, 2026"
2,“San Diego mosque shooters identified as trans...,Social Media,"May 19, 2026"
3,"Video shows U.S. Rep. Byron Donalds saying, “I...",X posts,"May 14, 2026"
4,An American passenger on the cruise ship invol...,X posts,"May 6, 2026"
5,“Florida is the only state in the nation kicki...,Kathy Castor,"April 29, 2026"
6,"In 2020, “Amy Acton called off Ohio’s election...",Vivek Ramaswamy,"April 24, 2026"
7,Imágenes muestran a personas “infectadas con H...,TikTok posts,"May 8, 2026"
8,"“Today, there are more children sleeping in Ne...",Christine Quinn,"March 5, 2026"
9,“The average IRS tax refund is up 11% compared...,Nicholas Langworthy,"March 31, 2026"
10,Gasoline prices have “come down very substanti...,Donald Trump,"May 7, 2026"
11,Congress passed the 1965 Voting Rights Act bec...,Byron Donalds,"May 4, 2026"
12,Republicans “want you to pay $1 Billion for a ...,Marcy Kaptur,"May 5, 2026"
13,Proposed data centers in New York state would ...,Liz Krueger,"March 5, 2026"
14,“California only has ‘enough’ oil and gas supp...,X posts,"May 6, 2026"
15,"“Consumer confidence is way up.""",Donald Trump,"May 4, 2026"
16,"From January 2025 to January 2026, “hate crime...",Sam Sutton,"March 11, 2026"
17,"“Under federal law, you cannot engage in parti...",Fentrice Driskell,"April 29, 2026"
18,Imagen muestra que “950 inmigrantes derrumbaro...,Instagram posts,"April 26, 2026"
19,“As a result of the 'Big Beautiful Bill' 15 mi...,Bernie Sanders,"April 22, 2026"
20,“Secret Service remains unpaid” during the par...,Tim Scott,"April 26, 2026"
21,“Graham Platner blames Maine’s women for getti...,Pine Tree Results PAC,"April 26, 2026"
22,Video shows “unedited raw security footage” of...,Social Media,"April 26, 2026"
23,“We are right now producing more oil than Saud...,Donald Trump,"April 23, 2026"
24,"Since the 2020 census, Florida has ""moved from...",Ron DeSantis,"April 27, 2026"
25,"“Tras el atentado a Trump”, en la cena de corr...",Social Media,"April 26, 2026"
26,"U.S. Rep. Byron Donalds voted ""against three p...",Jay Collins,"April 20, 2026"
27,"""There's two ways of calculating percentage"" d...",Robert F. Kennedy Jr.,"April 22, 2026"
28,"“With one dose of ibogaine, more than 80% of p...",Joe Rogan,"April 18, 2026"
29,“Newly released FOIA door logs show that forme...,X posts,"April 21, 2026"

In [35]:
import numpy as np
website="Certified used Mercedes-Benz for sale.html"
file=open(website,encoding="utf-8")
res=file.read()
soup=BeautifulSoup(res,"html.parser")
name=[]
mileage=[]
price=[]
dealer_name=[]
rating=[]
review_count=[]
# names=soup.find_all('h2',class_="title")
# for name in names:
#     prod_name.append(name.text)
# print(prod_name)
cards=soup.find_all("div",class_="vehicle-card")
for card in cards:
    name.append(card.h2.text)
    mileage.append(card.find('div',class_="mileage").text)
    price.append(card.find('span',class_="primary-price").text)
    try:
        
        rating.append(card.find('span',class_="sds-rating__count").text)
    except:
        rating.append(np.nan)

    dealer_name.append(card.find('div',class_="dealer-name").text.strip())
    review_count.append(card.find('span',class_="sds-rating__link sds-button-link").text)
data=pd.DataFrame({"name":name,
                  "mileage":mileage,
                  "price":price,
                  "rating":rating,
                  "review_count":review_count,
                  "dealer_name":dealer_name,
                  })
data

,name,mileage,price,rating,review_count,dealer_name
0,2020 Mercedes-Benz CLA 250 Base 4MATIC,"28,744 mi.","$35,995",4.4,(130 reviews),Mercedes-Benz of Lynnwood
1,2019 Mercedes-Benz AMG GT 53 Base,"25,771 mi.","$79,995",4.0,(117 reviews),International Autos
2,2021 Mercedes-Benz AMG GLE 53 Base,"22,374 mi.","$80,923",2.8,(38 reviews),John Sisson Motors
3,2022 Mercedes-Benz AMG CLA 45 Base 4MATIC,"10,595 mi.","$56,633",NaN,(30 reviews),Mercedes-Benz of Santa Rosa
4,2021 Mercedes-Benz AMG GLE 53 Base,"33,622 mi.","$76,995",4.7,(152 reviews),Mercedes-Benz of Rochester
5,2021 Mercedes-Benz E-Class E 450 4MATIC,"12,477 mi.","$76,532",4.5,"(5,283 reviews)",Benzel-Busch Motor Car
6,2021 Mercedes-Benz AMG GLE 63 S-Model 4MATIC,"22,383 mi.","$102,990",4.8,(174 reviews),Mercedes-Benz of Lancaster
7,2019 Mercedes-Benz S-Class S 560,"49,332 mi.","$54,580",4.8,"(2,016 reviews)",Mercedes-Benz of Ontario
8,2021 Mercedes-Benz AMG GLE 53 Base,"37,688 mi.","$76,715",2.8,(38 reviews),John Sisson Motors
9,2021 Mercedes-Benz GLA 250 Base,"19,521 mi.","$34,999",4.6,(264 reviews),Mercedes-Benz of Augusta
10,2022 Mercedes-Benz AMG C 43 Base 4MATIC,"14,420 mi.","$62,991",4.8,"(1,327 reviews)",Mercedes-Benz of Chicago
11,2018 Mercedes-Benz AMG C 43 Base 4MATIC,"34,555 mi.","$39,999",4.4,"(1,388 reviews)",Mercedes-Benz of South Orlando
12,2021 Mercedes-Benz E-Class E 450 4MATIC,"16,474 mi.","$74,998",4.8,(226 reviews),Contemporary Motor Cars Inc.
13,2021 Mercedes-Benz S-Class S 580 4MATIC,"10,233 mi.","$99,822",4.5,"(2,788 reviews)",Mercedes-Benz of Fort Washington
14,2022 Mercedes-Benz GLE 450 AWD 4MATIC,"6,800 mi.","$73,990",4.8,"(1,327 reviews)",Mercedes-Benz of Chicago
15,2018 Mercedes-Benz GLC 300 Base 4MATIC,"54,467 mi.","$29,151",4.5,"(2,788 reviews)",Mercedes-Benz of Fort Washington
16,2022 Mercedes-Benz AMG GLA 35 Base,"8,690 mi.","$49,736",4.5,"(2,788 reviews)",Mercedes-Benz of Fort Washington
17,2022 Mercedes-Benz GLB 250 Base,"8,158 mi.","$42,000",4.1,"(3,521 reviews)",Mercedes-Benz Of Tampa
18,2022 Mercedes-Benz S-Class S 500 4MATIC,"8,401 mi.","$86,986",4.5,"(1,016 reviews)",Mercedes-Benz of Walnut Creek
19,2020 Mercedes-Benz AMG S 63 Base 4MATIC,"24,958 mi.","$105,997",4.8,"(1,000 reviews)",Autobahn Motors
20,2021 Mercedes-Benz GLC 300 Base 4MATIC,"49,278 mi.","$37,280",4.2,(292 reviews),Bergstrom Luxury on Victory Lane